### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Michele404** [cruisediary/Comets#1]
Can't find Comets on Cocoapods

**Comment by cruisediary** [comment]
@Michele404 Thank you for your reporting issue
please check this step

**first** update CocoaPods repo because this library updated recently
```ruby
pod repo update 
```

**second** check your CocoaPods iOS version it require more than iOS 9 :)

**Comment by cruisediary** [comment]
@Michele404 I will add example soon thank you :)

**Comment by cruisediary** [comment]
☄️  Now on Cocoapods https://cocoapods.org/pods/Comets

I close this issue and make example issue :)
