### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by nitinumaretiya123** [cruisediary/Comets#8]
on first run

**Comment by cruisediary** [comment]
Hi @nitinumaretiya123 

I guess this is Xcode problem 🤔 

please check this apple [docs](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/swift_4_2_release_notes_for_xcode_10)
> Workaround: Disable batch mode by adding a user-defined build setting named SWIFT_ENABLE_BATCH_MODE and set it to NO.
